from django.urls import path
from .views import (
     home, contact, login, logout_admin,index,
    view_donor, delete_donor, add_donor,
    view_people, delete_people, add_people, add_appointment, view_appointment, delete_appointment, addblood, apply, analytics, aboutus, blog, bloodsupplylevel, bloodavailability, bloodgroup, bloodpressure, bloodstorage, careers, canigiveblood, corporatechallenge, campregistration, disasterresponse, donorform, donorlist,faq, healthhistory, hemoglobin, howtogiveblood, inspiringhope, irondeficiency, mission, news, offers, outreach, partners, purpose, prepareandaftercare, readmore, request, reciept, rewardsprogram, setting, trys, volunteer, wheretogiveblood, whatwespecializein,
    
)

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('admin_login/', login, name='admin_login'),
    path('logout/', logout_admin, name='logout_admin'),
    path('index/', index, name='dashboard'),
    path('view_donor/', view_donor, name='view_donor'),
    path('add_donor/', add_donor, name='add_donor'),
    path('delete_donor/<int:pid>/', delete_donor, name='delete_donor'),  
    path('view_people/', view_people, name='view_people'),
    path('add_people/', add_people, name='add_people'),
    path('delete_people/<int:pid>/', delete_people, name='delete_people'),
    path('add_appointment/', add_appointment, name='add_appointment'),
    path('view_appointment/', view_appointment, name='view_appointment'),
    path('delete_appointment/<int:pid>/', delete_appointment, name='delete_appointment'),
    path('addblood/', addblood, name='addblood'),
    path('apply/', apply, name='apply'),
    path('analytics/', analytics, name='analytics'),
    path('aboutus/', aboutus, name='aboutus'),
    path('blog/', blog, name='blog'),
    path('bloodsupplylevel/', bloodsupplylevel, name='bloodsupplylevel'),
    path('bloodavailability/', bloodavailability, name='bloodavailability'),
    path('bloodgroup/', bloodgroup, name='bloodgroup'),
    path('bloodpressure/', bloodpressure, name='bloodpressure'),
    path('bloodstorage/', bloodstorage, name='bloodstorage'),
    path('bloodsupplylevel/', bloodsupplylevel, name='bloodsupplylevel'),
    path('canigiveblood/', canigiveblood, name='canigiveblood'),
    path('careers/', careers, name='careers'),
    path('campregistration/', campregistration, name='campregistration'),
    path('corporatechallenge/', corporatechallenge, name='corporatechallenge'),
    path('disaster-response/', disasterresponse, name='disaster-response'),
    path('donorform/', donorform, name='donorform'),
    path('donorlist/', donorlist, name='donorlist'),
    path('faq/', faq, name='faq'),
    path('health-history/', healthhistory, name='health-history'),
    path('hemoglobin/', hemoglobin, name='hemoglobin'),
    path('howtogiveblood/', howtogiveblood, name='howtogiveblood'),
    path('inspiring-hope/', inspiringhope, name='inspiring-hope'),
    path('iron-deficiency/', irondeficiency, name='iron-deficiency'),
    path('mission/', mission, name='mission'),
    path('news/', news, name='news'),
    path('offers/', offers, name='offers'),
    path('outreach/', outreach, name='outreach'),
    path('partners/', partners, name='partners'),
    path('prepareandaftercare/', prepareandaftercare, name='prepareandaftercare'),
    path('purpose/', purpose, name='purpose'),
    path('readmore/', readmore, name='readmore'),
    path('request/', request, name='request'),
    path('reciept/', reciept, name='reciept'),
    path('rewards-program/', rewardsprogram, name='rewards-program'),
    path('setting/', setting, name='setting'),
    path('trys/', trys, name='trys'),
    path('volunteer/', volunteer, name='volunteer'),
    path('wheretogiveblood/', wheretogiveblood, name='wheretogiveblood'),
    path('whatwespecializein', whatwespecializein, name='whatwespecializein'),


]
