# Generated by Django 5.2.1 on 2025-08-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_people_alter_donor_mobile_alter_appointment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='special',
        ),
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(default='A+', max_length=5),
        ),
        migrations.AddField(
            model_name='donor',
            name='division',
            field=models.CharField(default='Chattogram', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='hb_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donor',
            name='medical_issue',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='rh_factor',
            field=models.CharField(default='+', max_length=2),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
