# Generated by Django 5.2.1 on 2025-08-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_donor_special_donor_address_donor_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='blood_component',
            field=models.CharField(default='Packed Cell', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(default='A+', max_length=5),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='number_of_bags',
            field=models.IntegerField(default=1),
        ),
    ]
