# Generated by Django 5.2.1 on 2025-08-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appointment_full_name_appointment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='number_of_bags',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hb_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='medical_issue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='rh_factor',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], default='+', max_length=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='people',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
