# Generated by Django 5.2.1 on 2025-08-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_appointment_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.AddField(
            model_name='people',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='people',
            name='surname',
            field=models.CharField(default='User', max_length=25),
        ),
    ]
